[package]
name = "cch23-klismas"
version = "0.4.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
shuttle-axum = "0.34.1"
shuttle-runtime = "0.34.1"
tracing = "0.1.40"
serde = { version = "1.0.193", features = ["derive"] }

[dev-dependencies]
tokio = "1.34.0"
hyper = "0.14.27"
#hyper = "1.0.1"
tower = "0.4.13"
